config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get '/up', to: 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# app/models/comment.rb

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_post_comments_counter
  after_destroy :update_post_comments_counter

  validates :text, presence: true

  private

  def update_post_comments_counter
    post.update(comments_counter: post.comments.count)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/models/like.rb
# app/models/like.rb

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_post_likes_counter
  after_destroy :update_post_likes_counter

  private

  def update_post_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
# app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.includes(:user).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.includes(:author).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    # Assign the comment to the current_user
    @comment.user = current_user

    return unless @comment.save

    redirect_to user_post_path(@post.author, @post), notice: 'Comment created successfully'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @like = Like.new(user: @user, post: @post)
    @like.save
    redirect_to user_post_path(user_id: @user.id, id: @post.id)
  end
end

app/controllers/posts_controller.rb
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:author).where(author_id: @user.id).paginate(page: params[:page], per_page: 10)
  end

  def show
    @post = Post.includes(:author, :comments).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      flash[:notice] = 'Your post was created successfully'
      redirect_to user_posts_url
    else
      flash.alert = 'Sorry, something went wrong!'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:posts).all
  end

  def show
    @user = User.includes(posts: :author).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def concat_strings(str1, str2)
    "#{str1} #{str2}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name(user)
    "#{user.first_name} #{user.last_name}"
  end

  def display_age(user)
    "Age: #{Time.now.year - user.birthdate.year}"
  end
end

app/views/comments/new.html.erb
<%= form_with(model: Comment.new, url: comments_path, method: :post) do |form| %>
  <%= form.text_area :content, placeholder: "Enter your comment here" %>
  <%= form.submit "Create Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "postindex" %>

<div class='page'>
  <div class='user'>
    <div class='photo'>
      <%= image_tag(@user.photo, alt: @user.name, class: "user-photo") if @user.photo.present? %>
    </div>
    <div class='userinfo'>
      <h2 class='username'><%= @user.name %></h2>
      <h4 class='postnumber'>Number of posts: <%= @user.posts.count %></h4>
      </div>

    <button class="see-all-post">
    <%= link_to "Create new post", new_user_post_path, class: "create-post-button" %>
</button>
  </div>
  <ul class='postlist'>
    <% @posts.each do |post| %>
      <li class='post'>
        <h3 class='order'><%= link_to "#{post.title}", user_post_path(post.author, post) %></h3></br>
        <p class='posttext'><%= post.text %></p>
        <p class='comments'>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
        <% post.instance_eval { recent_comments.includes(:user) }.each do |comment| %>
          <li class='comment-list'><strong><%= comment.user.name %> :</strong> <%= comment.text %></li></br>
        <% end %>
      </li>
    <% end %>
  </ul>
  <button type='button' class='button'><%= will_paginate @posts %> Pagination</button>
</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag "newpost" %>
<section>
  <h2>New Post</h2>
  <% if @post.errors.any? %>
    <div>
      <% @post.errors.full_messages.each do |message| %>
      <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <%= form_with model: [:user, @post], data: { turbo: false }, local: true do |form| %>
    <div>
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, required: true, autofocus: true, class: "form-input" %>
    </div>
    <div>
      <%= form.label :text, class: "form-label" %>
      <%= form.text_area :text, required: true, autofocus: true, class: "form-input" %>
    </div>
    <%= form.submit "submit", class: "form-button" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<%= stylesheet_link_tag "postshow" %>

<div class='open-post-flex'>
  <div class='open-post'>
    <div class='open-post-header'>
      <h3><%= @post.title %> by <%= @post.author.name %></h3>
      <p class='amount'>
        Comments: <%= @post.comments_counter %>,
        Likes: <%= @post.likes_counter %>,
        Liked by: <%= @post.likes.map { |like| like.user.name }.join(', ') %>
      </p>
    </div>
    <p class='text'><%= @post.text %></p>
  </div>

  <% @post.comments.includes(:user).each do |comment| %>
    <div class='open-comment'>
      <strong><%= comment.user.name %> :</strong> <%= comment.text %>
    </div>
  <% end %>

  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

  <%= form_with(model: Comment.new, url: user_post_comments_path(@post.author, @post), method: :post) do |form| %>
    <%= form.text_field :text, placeholder: "Enter your comment here" %>
    <%= form.submit "Create Comment" %>
  <% end %>

  <div>
    <%= form_with(model: @like, url: user_post_likes_path(@post.author, @post), method: :post, local: true) do |form| %>
      <%= form.submit 'Like post', class: 'submit' %>
    <% end %>
  </div>

app/views/users/index.html.erb
<%= stylesheet_link_tag "userindex" %>

<ul class='cardlist'>
  <% @users.each do |user| %>
    <li class='card'>
      <div class='userimage'>
        <%= link_to user_path(user) do %>
          <% if user.photo.attached? %>
            <%= image_tag user.photo.variant(resize: "100x100") %>
          <% else %>
            <%= image_tag "users.jpeg", alt: "Default Profile Image", width: 100, height: 100 %>
          <% end %>
        <% end %>
      </div>
      <div class='userinfo'>
        <%= link_to user_path(user) do %>
          <h2 class='username'><%= user.name %></h2>
        <% end %>
        <h3 class='postnumber'>Number of posts: <%= user.posts.count %></h3>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= stylesheet_link_tag "usershow" %>

<div class='idpage'>
  <div class='user'>
    <div class='photo'>
      <%= image_tag(@user.photo, alt: @user.name, class: "user-photo") if @user.photo.present? %>
    </div>
    <div class='userinfo'>
      <h2 class='username'><%= @user.name %></h2>
      <h4 class='postnumber'>Number of posts: <%= @user.posts.count %></h4>
    </div>
  </div>
  <div class='bio'>
    <h3 class='biohead'>Bio</h3></br>
    <p class='biotext'><%= @user.bio %></p>
  </div>
  <div class='button'>
  <%= link_to "Create new post", new_user_post_path(user_id: @user.id), class: "create-post-button" %>
</div>
  <ul class='postlist'>
    <% @user.posts.limit(3).each do |post| %>
      <li class='post'>
        <h3 class='order'><%= link_to post.title, user_post_path(post.author, post) %></h3></br>
        <p class='posttext'><%= post.text %></p>
        <p class='comments'>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
      </li>
    <% end %>
  </ul>

  <%= link_to "See all posts", user_posts_path(@user), class: 'button back' if @user.posts.count > 3 %>



  </div>